Enhance waitFor such that it can return a last "good" value.
blackboard/protractor-sync pull request #57
Opened 2018-02-15 00:16 UTC by scriby

This allows multiple expectations to be run based on the result of a polled wait.

2018-02-15 17:40 UTC, shermaneric commented on API.md
> +* **waitFor<T>(condition: () => { data: T, keepPolling: boolean })** - Waits fo the condition function to return { keepPolling: false } and returns the data element. An exception will be raised if it
I dig the flexibility of this, thanks @scriby !

2018-02-15 17:43 UTC, shermaneric commented on API.md
> +* **waitFor<T>(condition: () => { data: T, keepPolling: boolean })** - Waits fo the condition function to return { keepPolling: false } and returns the data element. An exception will be raised if it
@here: Thoughts about making this a 5.2.0 version as this seems to be adding new functionality?

2018-02-15 17:43 UTC, shermaneric approved these changes
Looks good!

2018-02-15 18:11 UTC, mindywhitsitt requested changes
Looks nice to me. Can you please also update the API.md file to describe the second way you can call `waitFor`?

2018-02-22 15:27 UTC, mindywhitsitt approved these changes
Sorry. I somehow missed that you had updated the API doc correctly already. Looks good.

2018-02-23 17:49 UTC, merged